In [8]:
##Task 01
numbers = [1,2,3,4]
even = []
odd = []
for x in numbers:
    if x%2==0:
        even.append(x**3)
    else:
        odd.append(x**2)


merged=sorted(even+odd)
print(numbers)
print(even)
print(odd)
print(merged)


[1, 2, 3, 4]
[8, 64]
[1, 9]
[1, 8, 9, 64]


In [16]:
##Task 02
Products = {}
for i in range (0,3):
    Prod_Name = input("Enter Product Name")
    Prod_Category = input("Enter Product Category")
    Price = int(input("Enter Price"))
    Products[i] = {
        "Product Name" : Prod_Name,
        "Product category" : Prod_Category,
        "Price" : Price
    }
    minimum_Product= min(Products.items(), key=lambda item: item[1]["Price"])
    maximum_Product=max(Products.items(), key=lambda item: item[1]["Price"])
    sorted_Products = sorted(Products.items(), key=lambda item: item[1]["Price"])

print(minimum_Product)
print(maximum_Product)
print(sorted_Products)
    
        


Enter Product Name a
Enter Product Category a
Enter Price 100
Enter Product Name b
Enter Product Category b
Enter Price 80
Enter Product Name c
Enter Product Category c
Enter Price 60


(2, {'Product Name': 'c', 'Product category': 'c', 'Price': 60})
(0, {'Product Name': 'a', 'Product category': 'a', 'Price': 100})
[(2, {'Product Name': 'c', 'Product category': 'c', 'Price': 60}), (1, {'Product Name': 'b', 'Product category': 'b', 'Price': 80}), (0, {'Product Name': 'a', 'Product category': 'a', 'Price': 100})]


In [22]:
##Task 03
import functools as ft
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even = list(filter(lambda x: x % 2 == 0, numbers))
print (even)
squared_evens = list(map(lambda x: x ** 2, even))
print(squared_evens)
result = ft.reduce(lambda x, y: x + y, squared_evens)
print("Sum of squares of even numbers:", result)


[2, 4, 6, 8, 10]
[4, 16, 36, 64, 100]
Sum of squares of even numbers: 220


In [29]:
##Task 5
import numpy as np

np.random.seed(42)
matrix = np.random.rand(6, 4)

print("Generated matrix:")
print(matrix)

print("\nShape:", matrix.shape)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

col_mean = matrix.mean(axis=0)
row_max = matrix.max(axis=1)

print("\nColumn-wise mean:", col_mean)
print("Row-wise maximum:", row_max)

max_index = np.unravel_index(matrix.argmax(), matrix.shape)
print("Index of maximum element:", max_index)


Generated matrix:
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]]

Shape: (6, 4)
Size: 24
Data type: float64

Column-wise mean: [0.48003526 0.4485618  0.28609611 0.54595666]
Row-wise maximum: [0.95071431 0.86617615 0.96990985 0.83244264 0.52475643 0.61185289]
Index of maximum element: (2, 3)


In [30]:
##Task 6
import numpy as np

scores = np.array([
    [85, 90, 78, 92],
    [72, 68, 80, 75],
    [95, 88, 91, 87],
    [65, 70, 62, 68]
])

print("Performance Scores Matrix:")
print(scores)
print("Rows = Systems, Columns = Test Cases")

system_averages = scores.mean(axis=1)

print("\nAverage Score per System:", system_averages)

ranking_indices = np.argsort(system_averages)[::-1]

print("\nSystem Ranking (Best to Worst):")
for rank, sys_idx in enumerate(ranking_indices, 1):
    print(f"Rank {rank}: System {sys_idx} (Avg: {system_averages[sys_idx]:.2f})")

print("\nSorted Averages:", system_averages[ranking_indices])

Performance Scores Matrix:
[[85 90 78 92]
 [72 68 80 75]
 [95 88 91 87]
 [65 70 62 68]]
Rows = Systems, Columns = Test Cases

Average Score per System: [86.25 73.75 90.25 66.25]

System Ranking (Best to Worst):
Rank 1: System 2 (Avg: 90.25)
Rank 2: System 0 (Avg: 86.25)
Rank 3: System 1 (Avg: 73.75)
Rank 4: System 3 (Avg: 66.25)

Sorted Averages: [90.25 86.25 73.75 66.25]
