## Lab Goals
- Understand why Python is used in AI
- Practice core Python data structures
- Learn functions, lambda expressions, and OOP
- Perform numerical computation using NumPy

## Variables and Data Types


In [1]:
x = 10
y = 3.5
name = "AI Lab"
is_active = True

type(x), type(y), type(name), type(is_active)


(int, float, str, bool)

## Lists in AI

In [6]:
states = ["A", "B", "C", "D","D"]
states[0]


'A'

In [7]:
states.append("E")
states.remove("B")
states


['A', 'C', 'D', 'D', 'E']

In [4]:
print(dir(states))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [10]:
print(states.count("D"))

2


In [4]:
numbers = [1, 2, 3, 4, 5]
numbers[::-1]


[5, 4, 3, 2, 1]

In [ ]:
start defaults to:

0 if step > 0

len(sequence)-1 if step < 0

stop defaults to:

len(sequence) if step > 0

-1 if step < 0

step = -1 (negative → reverse)

start not given → defaults to last index = len(numbers)-1 = 4

stop not given → defaults to before first element = -1 (exclusive)

In [5]:
squares = [x**2 for x in numbers]
squares


[1, 4, 9, 16, 25]

In [45]:
data = [10, 3.5, "AI", True]
data


[10, 3.5, 'AI', True]

## Slicing in Python

In [33]:
numbers = [10, 20, 30, 40, 50, 60]
numbers


[10, 20, 30, 40, 50, 60]

In [34]:
numbers[1:4]


[20, 30, 40]

In [35]:
numbers[:3]


[10, 20, 30]

In [36]:
numbers[3:]


[40, 50, 60]

In [37]:
numbers[::-1]


[60, 50, 40, 30, 20, 10]

## Tuples in Python

In [2]:
point = (3, 4)
point


(3, 4)

In [3]:
type(point)


tuple

In [4]:
# Accessing elements
point[0], point[1]


(3, 4)

In [5]:
# Tuple unpacking
x, y = point
x, y


(3, 4)

In [2]:
# Trying to modify (will cause error)
 #point[0] = 10


## Dictionaries for State Representation


In [1]:
heuristic = {
    "A": 10,
    "B": 5,
    "C": 2
}

heuristic["B"]


5

In [2]:
heuristic["D"] = 1
heuristic["A"] = 8
heuristic


{'A': 8, 'B': 5, 'C': 2, 'D': 1}

In [3]:
for state, h in heuristic.items():
    print(state, h)


A 8
B 5
C 2
D 1


In [4]:
heuristic.get("E", "Not Found")


'Not Found'

In [16]:
students = {}

for i in range(0, 2):
    name = input("Enter your name: ") #user input
    reg = input("Enter registration: ")
    gpa = float(input("Enter gpa: "))

    students[i] = {
        "Student_Name": name,
        "Student_Category": reg,
        "GPA": gpa
    }


Enter your name:  abc
Enter registration:  25i3459
Enter gpa:  3.4
Enter your name:  xyz
Enter registration:  23i3421
Enter gpa:  2.6


In [17]:
students[1]

{'Student_Name': 'xyz', 'Student_Category': '23i3421', 'GPA': 2.6}

In [24]:
sorted_students = sorted(students.items(), key=lambda item: item[1]["GPA"])
print(sorted_students)

[(1, {'Student_Name': 'xyz', 'Student_Category': '23i3421', 'GPA': 2.6}), (0, {'Student_Name': 'abc', 'Student_Category': '25i3459', 'GPA': 3.4})]


## Functions

In [14]:
def cost(a, b):
    return abs(a - b)

cost(10, 3)


7

## Lambda Functions


In [16]:
heuristic = lambda x: x * 2
heuristic(5)


10

In [18]:
avg=lambda x,y,z:(x+y+z)/3
print(avg(3,4,5))

4.0


In [20]:
nodes = [("A", 10), ("B", 5), ("C", 2)]
sorted(nodes, key=lambda x: x[1])


[('C', 2), ('B', 5), ('A', 10)]

In [22]:
def get_second(item): #without lambda
    return item[1]

sorted(nodes, key=get_second)


[('C', 2), ('B', 5), ('A', 10)]

# Map

In [4]:
lst=[1,2,3,4,5]
t=list(map(lambda x:x**3,lst))
print(t)

                      

[1, 8, 27, 64, 125]


# Filter

In [5]:
t=list(filter(lambda x:x>2,lst))
print(t)

[3, 4, 5]


# Reduce

In [28]:
from functools import reduce

n = [1, 2, 3, 4, 5, 6]

res = reduce(lambda x, y: x + y, n)

print(res)

21


# sets

In [31]:
Devices={"laptop","Mobile",}
print(Devices)
Devices.add("Tablet")
print(Devices)
Devices.remove("laptop")
print(Devices)

{'Mobile', 'laptop'}
{'Tablet', 'Mobile', 'laptop'}
{'Tablet', 'Mobile'}


## Object-Oriented Programming for AI


In [35]:
class Agent:
    def __init__(self, name):
        self.name = name

    def act(self, percept):
        return f"{self.name} received {percept}"


In [36]:
agent1 = Agent("SimpleAgent")
agent1.act("clean")


'SimpleAgent received clean'

## NumPy for AI Computation


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr


array([1, 2, 3, 4])

In [34]:
arr.shape, arr.size, arr.dtype


((4,), 4, dtype('int64'))

In [35]:
random_matrix = np.random.rand(3, 3)
random_matrix


array([[0.39423336, 0.79779349, 0.69694043],
       [0.99545191, 0.63368763, 0.70216569],
       [0.6676963 , 0.43725179, 0.78313942]])

## Vector Operations (No Loops!)

In [37]:
a = np.array([1, 2, 3,2])
b = np.array([4, 5, 6,6])

a + b


array([5, 7, 9, 8])

In [38]:
a * b


array([ 4, 10, 18, 12])

In [40]:
np.sum(a), np.max(a), np.argmax(b)


(np.int64(8), np.int64(3), np.int64(2))

In [41]:
max_idx = int(np.argmax(b)) 
print("max:",max_idx)

max: 2


## Matrix Operations (ML Foundation)

In [46]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

np.dot(A, B)


array([[19, 22],
       [43, 50]])

In [22]:
A.T


array([[1, 3],
       [2, 4]])

In [23]:
np.linalg.det(A)


np.float64(-2.0000000000000004)

# Statistics (Data Understanding)

In [48]:
data = np.array([10, 20, 30, 40])

np.mean(data), np.std(data)


(np.float64(25.0), np.float64(11.180339887498949))

In [49]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

np.mean(matrix, axis=0)
np.mean(matrix, axis=1)


array([20.0, 50.0])

In [53]:
# np.set_printoptions(precision=1, floatmode='fixed')
# print(np.mean(matrix, axis=1))


[20.0 50.0]
